config/routes.rb
Rails.application.routes.draw do
  resources :games

  root 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  def avg_length_hour
    avg_length_min / 60.0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :min_players, :max_players, :difficulty, :avg_length_min, :description, :genre, :mechanics)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :min_players %><br>
    <%= f.number_field :min_players %>
  </div>
  <div class="field">
    <%= f.label :max_players %><br>
    <%= f.number_field :max_players %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.number_field :difficulty %>
  </div>
  <div class="field">
    <%= f.label :avg_length_min %><br>
    <%= f.number_field :avg_length_min %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :mechanics %><br>
    <%= f.text_area :mechanics %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Min players</th>
      <th>Max players</th>
      <th>Difficulty</th>
      <th>Avg. Length (Min)</th>
      <th>Description</th>
      <th>Genre</th>
      <th>Mechanics</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <td><%= game.min_players %></td>
        <td><%= game.max_players %></td>
        <td><%= game.difficulty %></td>
        <td><%= game.avg_length_min %></td>
        <td><%= game.description %></td>
        <td><%= game.genre %></td>
        <td><%= game.mechanics %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'JSON', game_path(game, :format => :json) %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<p>
  <strong>Min players:</strong>
  <%= @game.min_players %>
</p>

<p>
  <strong>Max players:</strong>
  <%= @game.max_players %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @game.difficulty %>
</p>

<p>
  <strong>Average Length (minutes):</strong>
  <%= @game.avg_length_min %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @game.genre %>
</p>

<p>
  <strong>Mechanics:</strong>
  <%= @game.mechanics %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BGDB -- Board Game Database</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>